CREATE TABLE "public"."DriverFeedback" (
  "feedback_id"  integer                     GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "driver_id"    integer                     NOT NULL,
  "rating"       integer                     NOT NULL,
  "submitted_at" timestamp without time zone NOT NULL,
  CONSTRAINT "DriverFeedback_pkey" PRIMARY KEY (feedback_id),
  CONSTRAINT "chk_driverfeedback_rating" CHECK (((rating >= 1) AND (rating <= 5)))
);

ALTER TABLE "public"."DriverFeedback"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."Driver" (
  "driver_id"   integer           GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "driver_name" character varying NOT NULL,
  CONSTRAINT "Driver_pkey" PRIMARY KEY (driver_id)
);

ALTER TABLE "public"."Driver"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."GPSLocation" (
  "gpa_location_id" bigint                      GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "shuttle_id"      bigint                      NOT NULL,
  "latitude"        numeric                     NOT NULL,
  "longitude"       numeric                     NOT NULL,
  "speed"           numeric,
  "heading"         numeric,
  "recorded_at"     timestamp without time zone NOT NULL,
  CONSTRAINT "GPSLocation_pkey" PRIMARY KEY (gpa_location_id),
  CONSTRAINT "chk_gps_latitude" CHECK (((latitude >= ('-90'::integer)::numeric) AND (latitude <= (90)::numeric))),
  CONSTRAINT "chk_gps_longitude" CHECK (((longitude >= ('-180'::integer)::numeric) AND (longitude <= (180)::numeric)))
);

ALTER TABLE "public"."GPSLocation"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."Occupancy" (
  "occupancy_id"    bigint                      GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "shuttle_id"      bigint                      NOT NULL,
  "boarding_count"  bigint                      NOT NULL,
  "exiting_count"   bigint                      NOT NULL,
  "passenger_count" bigint                      NOT NULL,
  "recorded_at"     timestamp without time zone NOT NULL,
  CONSTRAINT "Occupancy_pkey" PRIMARY KEY (occupancy_id),
  CONSTRAINT "chk_occupancy_boarding" CHECK ((boarding_count >= 0)),
  CONSTRAINT "chk_occupancy_exiting" CHECK ((exiting_count >= 0)),
  CONSTRAINT "chk_occupancy_passenger_count" CHECK ((passenger_count >= 0))
);

ALTER TABLE "public"."Occupancy"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."RouteStop" (
  "route_stop_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "stop_id"       bigint NOT NULL,
  "stop_order"    bigint NOT NULL,
  "route_id"      bigint NOT NULL,
  CONSTRAINT "RouteStop_pkey" PRIMARY KEY (route_stop_id),
  CONSTRAINT "uq_routestop_route_order" UNIQUE (route_id, stop_order),
  CONSTRAINT "uq_routestop_route_stop" UNIQUE (route_id, stop_id)
);

ALTER TABLE "public"."RouteStop"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."Route" (
  "route_id"   bigint            GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "route_name" character varying NOT NULL,
  "status"     character varying NOT NULL,
  CONSTRAINT "Route_pkey" PRIMARY KEY (route_id)
);

ALTER TABLE "public"."Route"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."Schedule" (
  "schedule_id"    bigint                 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "route_id"       bigint                 NOT NULL,
  "stop_id"        bigint                 NOT NULL,
  "departure_time" time without time zone NOT NULL,
  "day_of_week"    character varying      NOT NULL,
  CONSTRAINT "Schedule_pkey" PRIMARY KEY (schedule_id)
);

ALTER TABLE "public"."Schedule"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."Shuttle" (
  "shuttle_id"         bigint            GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "route_id"           bigint            NOT NULL,
  "vehicle_number"     character varying NOT NULL,
  "bus_type"           character varying,
  "capacity"           bigint            NOT NULL,
  "current_passengers" bigint            NOT NULL,
  "status"             character varying NOT NULL,
  "driver_id"          bigint,
  CONSTRAINT "Shuttle_pkey" PRIMARY KEY (shuttle_id),
  CONSTRAINT "chk_shuttle_capacity" CHECK ((capacity > 0)),
  CONSTRAINT "chk_shuttle_current_passengers" CHECK (((current_passengers >= 0) AND (current_passengers <= capacity)))
);

ALTER TABLE "public"."Shuttle"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."Stop" (
  "stop_id"   bigint            GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "stop_name" character varying NOT NULL,
  "latitude"  numeric           NOT NULL,
  "longitude" numeric           NOT NULL,
  CONSTRAINT "Stop_pkey" PRIMARY KEY (stop_id)
);

ALTER TABLE "public"."Stop"
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."DriverFeedback"
  ADD CONSTRAINT "DriverFeedback_driver_id_fkey" FOREIGN KEY (driver_id) REFERENCES public."Driver"(driver_id);

ALTER TABLE "public"."RouteStop"
  ADD CONSTRAINT "RouteStop_route_id_fkey" FOREIGN KEY (route_id) REFERENCES public."Route"(route_id);

ALTER TABLE "public"."Schedule"
  ADD CONSTRAINT "Schedule_route_id_fkey" FOREIGN KEY (route_id) REFERENCES public."Route"(route_id);

ALTER TABLE "public"."GPSLocation"
  ADD CONSTRAINT "GPSLocation_shuttle_id_fkey" FOREIGN KEY (shuttle_id) REFERENCES public."Shuttle"(shuttle_id);

ALTER TABLE "public"."Occupancy"
  ADD CONSTRAINT "Occupancy_shuttle_id_fkey" FOREIGN KEY (shuttle_id) REFERENCES public."Shuttle"(shuttle_id);

ALTER TABLE "public"."Shuttle"
  ADD CONSTRAINT "Shuttle_route_id_fkey" FOREIGN KEY (route_id) REFERENCES public."Route"(route_id);

ALTER TABLE "public"."Shuttle"
  ADD CONSTRAINT "fk_shuttle_driver" FOREIGN KEY (driver_id) REFERENCES public."Driver"(driver_id) ON DELETE SET NULL;

ALTER TABLE "public"."RouteStop"
  ADD CONSTRAINT "RouteStop_stop_id_fkey" FOREIGN KEY (stop_id) REFERENCES public."Stop"(stop_id);

ALTER TABLE "public"."Schedule"
  ADD CONSTRAINT "Schedule_stop_id_fkey" FOREIGN KEY (stop_id) REFERENCES public."Stop"(stop_id);

REVOKE ALL ON SEQUENCE "public"."DriverFeedback_feedback_id_seq" FROM "anon";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."DriverFeedback_feedback_id_seq" TO "anon";

REVOKE ALL ON SEQUENCE "public"."DriverFeedback_feedback_id_seq" FROM "authenticated";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."DriverFeedback_feedback_id_seq" TO "authenticated";

REVOKE ALL ON SEQUENCE "public"."DriverFeedback_feedback_id_seq" FROM "postgres";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."DriverFeedback_feedback_id_seq" TO "postgres";

REVOKE ALL ON SEQUENCE "public"."DriverFeedback_feedback_id_seq" FROM "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."DriverFeedback_feedback_id_seq" TO "service_role";

REVOKE ALL ON SEQUENCE "public"."Driver_driver_id_seq" FROM "anon";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."Driver_driver_id_seq" TO "anon";

REVOKE ALL ON SEQUENCE "public"."Driver_driver_id_seq" FROM "authenticated";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."Driver_driver_id_seq" TO "authenticated";

REVOKE ALL ON SEQUENCE "public"."Driver_driver_id_seq" FROM "postgres";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."Driver_driver_id_seq" TO "postgres";

REVOKE ALL ON SEQUENCE "public"."Driver_driver_id_seq" FROM "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."Driver_driver_id_seq" TO "service_role";

REVOKE ALL ON SEQUENCE "public"."GPSLocation_gpa_location_id_seq" FROM "anon";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."GPSLocation_gpa_location_id_seq" TO "anon";

REVOKE ALL ON SEQUENCE "public"."GPSLocation_gpa_location_id_seq" FROM "authenticated";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."GPSLocation_gpa_location_id_seq" TO "authenticated";

REVOKE ALL ON SEQUENCE "public"."GPSLocation_gpa_location_id_seq" FROM "postgres";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."GPSLocation_gpa_location_id_seq" TO "postgres";

REVOKE ALL ON SEQUENCE "public"."GPSLocation_gpa_location_id_seq" FROM "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."GPSLocation_gpa_location_id_seq" TO "service_role";

REVOKE ALL ON SEQUENCE "public"."Occupancy_occupancy_id_seq" FROM "anon";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."Occupancy_occupancy_id_seq" TO "anon";

REVOKE ALL ON SEQUENCE "public"."Occupancy_occupancy_id_seq" FROM "authenticated";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."Occupancy_occupancy_id_seq" TO "authenticated";

REVOKE ALL ON SEQUENCE "public"."Occupancy_occupancy_id_seq" FROM "postgres";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."Occupancy_occupancy_id_seq" TO "postgres";

REVOKE ALL ON SEQUENCE "public"."Occupancy_occupancy_id_seq" FROM "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."Occupancy_occupancy_id_seq" TO "service_role";

REVOKE ALL ON SEQUENCE "public"."RouteStop_route_stop_id_seq" FROM "anon";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."RouteStop_route_stop_id_seq" TO "anon";

REVOKE ALL ON SEQUENCE "public"."RouteStop_route_stop_id_seq" FROM "authenticated";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."RouteStop_route_stop_id_seq" TO "authenticated";

REVOKE ALL ON SEQUENCE "public"."RouteStop_route_stop_id_seq" FROM "postgres";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."RouteStop_route_stop_id_seq" TO "postgres";

REVOKE ALL ON SEQUENCE "public"."RouteStop_route_stop_id_seq" FROM "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."RouteStop_route_stop_id_seq" TO "service_role";

REVOKE ALL ON SEQUENCE "public"."Route_route_id_seq" FROM "anon";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."Route_route_id_seq" TO "anon";

REVOKE ALL ON SEQUENCE "public"."Route_route_id_seq" FROM "authenticated";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."Route_route_id_seq" TO "authenticated";

REVOKE ALL ON SEQUENCE "public"."Route_route_id_seq" FROM "postgres";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."Route_route_id_seq" TO "postgres";

REVOKE ALL ON SEQUENCE "public"."Route_route_id_seq" FROM "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."Route_route_id_seq" TO "service_role";

REVOKE ALL ON SEQUENCE "public"."Schedule_schedule_id_seq" FROM "anon";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."Schedule_schedule_id_seq" TO "anon";

REVOKE ALL ON SEQUENCE "public"."Schedule_schedule_id_seq" FROM "authenticated";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."Schedule_schedule_id_seq" TO "authenticated";

REVOKE ALL ON SEQUENCE "public"."Schedule_schedule_id_seq" FROM "postgres";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."Schedule_schedule_id_seq" TO "postgres";

REVOKE ALL ON SEQUENCE "public"."Schedule_schedule_id_seq" FROM "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."Schedule_schedule_id_seq" TO "service_role";

REVOKE ALL ON SEQUENCE "public"."Shuttle_shuttle_id_seq" FROM "anon";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."Shuttle_shuttle_id_seq" TO "anon";

REVOKE ALL ON SEQUENCE "public"."Shuttle_shuttle_id_seq" FROM "authenticated";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."Shuttle_shuttle_id_seq" TO "authenticated";

REVOKE ALL ON SEQUENCE "public"."Shuttle_shuttle_id_seq" FROM "postgres";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."Shuttle_shuttle_id_seq" TO "postgres";

REVOKE ALL ON SEQUENCE "public"."Shuttle_shuttle_id_seq" FROM "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."Shuttle_shuttle_id_seq" TO "service_role";

REVOKE ALL ON SEQUENCE "public"."Stop_stop_id_seq" FROM "anon";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."Stop_stop_id_seq" TO "anon";

REVOKE ALL ON SEQUENCE "public"."Stop_stop_id_seq" FROM "authenticated";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."Stop_stop_id_seq" TO "authenticated";

REVOKE ALL ON SEQUENCE "public"."Stop_stop_id_seq" FROM "postgres";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."Stop_stop_id_seq" TO "postgres";

REVOKE ALL ON SEQUENCE "public"."Stop_stop_id_seq" FROM "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."Stop_stop_id_seq" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."Driver" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."Driver" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."Driver" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."Driver" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."DriverFeedback" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."DriverFeedback" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."DriverFeedback" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."DriverFeedback" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."GPSLocation" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."GPSLocation" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."GPSLocation" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."GPSLocation" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."Occupancy" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."Occupancy" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."Occupancy" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."Occupancy" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."Route" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."Route" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."Route" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."Route" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."RouteStop" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."RouteStop" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."RouteStop" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."RouteStop" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."Schedule" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."Schedule" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."Schedule" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."Schedule" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."Shuttle" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."Shuttle" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."Shuttle" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."Shuttle" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."Stop" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."Stop" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."Stop" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."Stop" TO "service_role";

